import { GuitarType, StringsCount } from "./const";

const guitars = [
  {
    id: 1,
    reference: 'SO757575',
    name: 'Честер Bass',
    type: GuitarType.ELECTRO,
    reviewsCount: 15,
    rating: 4.5,
    stringsCount: StringsCount.SEVEN,
    price: 17500,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 2,
    reference: 'TK129049',
    name: 'СURT Z300',
    type: GuitarType.ELECTRO,
    reviewsCount: 9,
    rating: 4,
    stringsCount: StringsCount.SEVEN,
    price: 29500,
    image: "../img/electro-2.png",
    amount: 1,
  },
  {
    id: 3,
    reference: 'RO111111',
    name: 'Roman LX',
    type: GuitarType.UKULELE,
    reviewsCount: 21,
    rating: 4,
    stringsCount: StringsCount.FOUR,
    price: 6800,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 4,
    reference: 'TK436457',
    name: 'СURT T300',
    type: GuitarType.ELECTRO,
    reviewsCount: 15,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 30000,
    image: "../img/electro-3.png",
    amount: 1,
  },
  {
    id: 5,
    reference: 'DI192138',
    name: 'Dania Super',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 5,
    rating: 4,
    stringsCount: StringsCount.SEVEN,
    price: 3500,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 6,
    reference: 'SO934345',
    name: 'Честер WX ',
    type: GuitarType.ELECTRO,
    reviewsCount: 17,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 15300,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 7,
    reference: 'DI082347',
    name: 'Dania VX',
    type: GuitarType.UKULELE,
    reviewsCount: 5,
    rating: 4,
    stringsCount: StringsCount.FOUR,
    price: 2200,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 8,
    reference: 'SO135646',
    name: 'Честер Plus ',
    type: GuitarType.ELECTRO,
    reviewsCount: 27,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 30000,
    image: "../img/electro-4.png",
    amount: 1,
  },
  {
    id: 9,
    reference: 'VO154751',
    name: 'Виолана 300',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 3,
    rating: 4,
    stringsCount: StringsCount.SEVEN,
    price: 1700,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 10,
    reference: 'TK244556',
    name: 'СURT Clasic',
    type: GuitarType.ELECTRO,
    reviewsCount: 20,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 23000,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 11,
    reference: 'TK134663',
    name: 'СURT Z250',
    type: GuitarType.ELECTRO,
    reviewsCount: 19,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 18700,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 12,
    reference: 'SO123212',
    name: 'Честер 7X',
    type: GuitarType.ELECTRO,
    reviewsCount: 30,
    rating: 4.5,
    stringsCount: StringsCount.SEVEN,
    price: 35000,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 13,
    reference: 'SO123234',
    name: 'Честер 6V',
    type: GuitarType.ELECTRO,
    reviewsCount: 28,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 14900,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 14,
    reference: 'VO519510',
    name: 'Виолана Mix',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 7,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 7600,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 15,
    reference: 'VO457369',
    name: 'Виолана 250x',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 19,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 6500,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 16,
    reference: 'FB625903',
    name: 'Фабио Лайт',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 26,
    rating: 4.5,
    stringsCount: StringsCount.SEVEN,
    price: 12000,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 17,
    reference: 'FB576948',
    name: 'Фабио L100',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 31,
    rating: 4.5,
    stringsCount: StringsCount.SEVEN,
    price: 9900,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 18,
    reference: 'LU012032',
    name: 'Liana Z200',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 28,
    rating: 4.5,
    stringsCount: StringsCount.TWELVE,
    price: 8900,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 19,
    reference: 'LU546853',
    name: 'Liana Z100',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 34,
    rating: 4.5,
    stringsCount: StringsCount.TWELVE,
    price: 10500,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 20,
    reference: 'LU458283',
    name: 'Liana Z300',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 9,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 13300,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
  {
    id: 21,
    reference: 'RO324341',
    name: 'Roman RX',
    type: GuitarType.UKULELE,
    reviewsCount: 37,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 4800,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 22,
    reference: 'RO214235',
    name: 'Roman TX',
    type: GuitarType.UKULELE,
    reviewsCount: 5,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 1900,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 23,
    reference: 'DI132414',
    name: 'Dania U100',
    type: GuitarType.UKULELE,
    reviewsCount: 23,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 2500,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 24,
    reference: 'DI934754',
    name: 'Dania WR',
    type: GuitarType.UKULELE,
    reviewsCount: 3,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 3800,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 25,
    reference: 'DI034292',
    name: 'Dania LE',
    type: GuitarType.UKULELE,
    reviewsCount: 10,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 4100,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 26,
    reference: 'MI193214',
    name: 'Mirana V10',
    type: GuitarType.UKULELE,
    reviewsCount: 14,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 2700,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 27,
    reference: 'VO043244',
    name: 'Виолана Mini',
    type: GuitarType.ELECTRO,
    reviewsCount: 29,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 6700,
    image: "../img/electro-1.png",
    amount: 1,
  },
  {
    id: 28,
    reference: 'DI9634754',
    name: 'Dania WR',
    type: GuitarType.UKULELE,
    reviewsCount: 3,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 3800,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 29,
    reference: 'DI7034292',
    name: 'Dania LE',
    type: GuitarType.UKULELE,
    reviewsCount: 10,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 4100,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 30,
    reference: 'MI1934214',
    name: 'Mirana V10',
    type: GuitarType.UKULELE,
    reviewsCount: 14,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 2700,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 31,
    reference: 'VO0443244',
    name: 'Виолана Mini',
    type: GuitarType.UKULELE,
    reviewsCount: 29,
    rating: 4.5,
    stringsCount: StringsCount.FOUR,
    price: 6700,
    image: "../img/ukulele-1.png",
    amount: 1,
  },
  {
    id: 32,
    reference: 'VO4576369',
    name: 'Виолана 250x',
    type: GuitarType.ACOUSTIC,
    reviewsCount: 19,
    rating: 4.5,
    stringsCount: StringsCount.SIX,
    price: 6500,
    image: "../img/acoustic-1.png",
    amount: 1,
  },
];

export {guitars}